#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-$(CONFIG_SOC_SFA18_MPW0)    += sfa18_mpw0/
obj-$(CONFIG_SOC_SFA18_MPW1)    += sfa18_mpw1/
obj-$(CONFIG_SOC_SFA18_FULLMASK)    += sfa18_fullmask/
obj-$(CONFIG_SOC_SFA28)    += sfa28/
obj-$(CONFIG_SFA18_PCBA_TEST) += pcba-test/
