/*
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 */

#include <linux/module.h>
#include <linux/platform_device.h>
#include <linux/clk.h>
#include <linux/mmc/host.h>
#include <linux/mmc/dw_mmc.h>
#include <linux/of_address.h>
#include <sf16a18.h>

#include "dw_mmc.h"
#include "dw_mmc-pltfm.h"

#define SFAX8_CLKGEN_DIV       1

static void dw_mci_sfax8_prepare_command(struct dw_mci *host, u32 *cmdr)
{
	*cmdr |= SDMMC_CMD_USE_HOLD_REG;
}

static int dw_mci_sfax8_setup_clock(struct dw_mci *host)
{
	host->bus_hz /= SFAX8_CLKGEN_DIV;

	return 0;
}

/* Set mmc clk by internal clk_div instead of setting sdhc_clk. */
//#define SDHCCLK_MUX
#ifdef SDHCCLK_MUX
static void dw_mci_sfax8_set_ios(struct dw_mci *host, struct mmc_ios *ios)
{
	int ret;
	unsigned int cclkin;
	u32 bus_hz;

	/*
	 * cclkin: source clock of mmc controller
	 * bus_hz: card interface clock generated by CLKGEN
	 * bus_hz = cclkin / SFAX8_CLKGEN_DIV
	 * ios->clock = (div == 0) ? bus_hz : (bus_hz / (2 * div))
	 *
	 * Note: div can only be 0 or 1
	 *       if DDR50 8bit mode(only emmc work in 8bit mode),
	 *       div must be set 1
	 */
	if (ios->bus_width == MMC_BUS_WIDTH_8 &&
	    ios->timing == MMC_TIMING_MMC_DDR52)
		cclkin = 2 * ios->clock * SFAX8_CLKGEN_DIV;
	else
		cclkin = ios->clock * SFAX8_CLKGEN_DIV;

	ret = clk_set_rate(host->ciu_clk, cclkin);
	if (ret)
		dev_warn(host->dev, "failed to set rate %uHz\n", ios->clock);

	bus_hz = clk_get_rate(host->ciu_clk) / SFAX8_CLKGEN_DIV;
	if (bus_hz != host->bus_hz) {
		host->bus_hz = bus_hz;
		/* force dw_mci_setup_bus() */
		host->current_speed = 0;
	}
}
#endif

static const struct dw_mci_drv_data sfax8_drv_data = {
	.prepare_command        = dw_mci_sfax8_prepare_command,
#ifdef SDHCCLK_MUX
	.set_ios		= dw_mci_sfax8_set_ios,
#endif
	.setup_clock    = dw_mci_sfax8_setup_clock,
};

static const struct of_device_id dw_mci_sfax8_match[] = {
	{ .compatible = "siflower,sfax8-mmc",
		.data = &sfax8_drv_data },
	{},
};
MODULE_DEVICE_TABLE(of, dw_mci_sfax8_match);

static int dw_mci_sfax8_probe(struct platform_device *pdev)
{
	const struct dw_mci_drv_data *drv_data;
	const struct of_device_id *match;

	if (!pdev->dev.of_node)
		return -ENODEV;

	match = of_match_node(dw_mci_sfax8_match, pdev->dev.of_node);
	drv_data = match->data;

	return dw_mci_pltfm_register(pdev, drv_data);
}

#ifdef CONFIG_PM_SLEEP
static int dw_mci_sfax8_suspend(struct device *dev)
{
	struct dw_mci *host = dev_get_drvdata(dev);

	return dw_mci_suspend(host);
}

static int dw_mci_sfax8_resume(struct device *dev)
{
	struct dw_mci *host = dev_get_drvdata(dev);

	return dw_mci_resume(host);
}
#endif /* CONFIG_PM_SLEEP */

static SIMPLE_DEV_PM_OPS(dw_mci_sfax8_pmops,
			 dw_mci_sfax8_suspend,
			 dw_mci_sfax8_resume);

int dw_mci_sfax8_remove(struct platform_device *pdev)
{
	int ret;
	ret = dw_mci_pltfm_remove(pdev);

	return ret;
}

static struct platform_driver dw_mci_sfax8_pltfm_driver = {
	.probe		= dw_mci_sfax8_probe,
	.remove		= dw_mci_sfax8_remove,
	.driver		= {
		.name		= "dwmmc_sfax8",
		.of_match_table	= dw_mci_sfax8_match,
		.pm		= &dw_mci_sfax8_pmops,
	},
};

module_platform_driver(dw_mci_sfax8_pltfm_driver);

MODULE_AUTHOR("Mark Cai <mark.cai@siflower.com.cn>");
MODULE_ALIAS("platform:dwmmc-sfax8");
MODULE_LICENSE("GPL v2");
