obj-$(CONFIG_SND_SOC_SFAX8_I2S) += sfax8_i2s.o

snd-soc-sfax8-pcm-objs := sfax8-pcm.o
snd-soc-sfax8-spdif-objs := sfax8_spdif.o
obj-$(CONFIG_SND_SOC_SFAX8_PCM) += snd-soc-sfax8-pcm.o
obj-$(CONFIG_SND_SOC_SFAX8_SPDIF) += snd-soc-sfax8-spdif.o

# machine codes

snd-soc-sfax8-machine-objs := sfax8-machine.o
snd-soc-sfax8-spdif-machine-objs := sfax8-spdif-machine.o
obj-$(CONFIG_SND_SOC_SFAX8_MACHINE) += snd-soc-sfax8-machine.o
obj-$(CONFIG_SND_SOC_SFAX8_SPDIF_MACHINE) += snd-soc-sfax8-spdif-machine.o
