/*
 * This file is subject to the terms and conditions of the GNU General Public
 * License.  See the file "COPYING" in the main directory of this archive
 * for more details.
 *
 * Copyright (C) 2000,2012 MIPS Technologies, Inc.  All rights reserved.
 *	Carsten Langgaard <carstenl@mips.com>
 *	Steven J. Hill <sjhill@mips.com>
 */
#ifndef _MIPS_SF16A18INT_H
#define _MIPS_SF16A18INT_H

#define MIPS_GIC_IRQ_BASE	(MIPS_CPU_IRQ_BASE + 8)

/*
 * Interrupts 0..15 are used for sf16a18 ISA compatible interrupts
 */
#define SF16A18_INT_BASE		0

/* CPU interrupt offsets */
#define MIPSCPU_INT_SW0		0
#define MIPSCPU_INT_SW1		1
#define MIPSCPU_INT_MB0		2
#define MIPSCPU_INT_I8259A	MIPSCPU_INT_MB0
#define MIPSCPU_INT_MB1		3
#define MIPSCPU_INT_SMI		MIPSCPU_INT_MB1
#define MIPSCPU_INT_IPI0	MIPSCPU_INT_MB1 /* GIC IPI */
#define MIPSCPU_INT_MB2		4
#define MIPSCPU_INT_IPI1	MIPSCPU_INT_MB2 /* GIC IPI */
#define MIPSCPU_INT_MB3		5
#define MIPSCPU_INT_COREHI	MIPSCPU_INT_MB3
#define MIPSCPU_INT_MB4		6
#define MIPSCPU_INT_CORELO	MIPSCPU_INT_MB4

/* External Interrupts used for IPI */
#define GIC_IPI_EXT_INTR_RESCHED_VPE0	16
#define GIC_IPI_EXT_INTR_CALLFNC_VPE0	17
#define GIC_IPI_EXT_INTR_RESCHED_VPE1	18
#define GIC_IPI_EXT_INTR_CALLFNC_VPE1	19
#define GIC_IPI_EXT_INTR_RESCHED_VPE2	20
#define GIC_IPI_EXT_INTR_CALLFNC_VPE2	21
#define GIC_IPI_EXT_INTR_RESCHED_VPE3	22
#define GIC_IPI_EXT_INTR_CALLFNC_VPE3	23

/* SF16A18 UART Interrupts */
#define SF16A18_UART_FIFOSIZE (32)
#define SF16A18_UART_CLK (60000000)
#define SF16A18_UART_BASEADDR    (0x18300000)
#define SF16A18_UART_ENDADDR     (0x18303999)
#define SF16A18_UART0_IRQ    (226+MIPS_GIC_IRQ_BASE)

/* SF16A18 ETH Interrupts */
//TODO: this is hif irq, should add bmu_irq
#define SF16A18_ETH_IRQ    (16+MIPS_GIC_IRQ_BASE)
#define SF16A18_ETH_BASEADDR (0x10000000)
#define SF16A18_ETH_ENDADDR (0x106CFFFF)

/*SF16A18 GMAC Interrupts */
#define SF16A18_GMAC_SBD_IRQ			(32 + MIPS_GIC_IRQ_BASE)
#define SF16A18_GMAC_LPI_IRQ			(33 + MIPS_GIC_IRQ_BASE)
#define SF16A18_GMAC_PMT_IRQ			(34 + MIPS_GIC_IRQ_BASE)
#define SF16A18_GMAC_BASEADDR			0x10800000
#define SF16A18_GMAC_ENDADDR			0x109FFFFF

#define SIFLOWER_WIFI_INTC_CPU_SINGLE	 (48 + MIPS_GIC_IRQ_BASE)
//WIFI Inter Processor Communication
#define SIFLOWER_WIFI_INTC_IPC_HOST      (49 + MIPS_GIC_IRQ_BASE)

//WIFI End Of Transfer interrupts: Last fragment of the channel link list has been processed
#define SIFLOWER_WIFI_INTC_DMA_CH0_EOT   (50 + MIPS_GIC_IRQ_BASE)
#define SIFLOWER_WIFI_INTC_DMA_CH1_EOT   (51 + MIPS_GIC_IRQ_BASE)
#define SIFLOWER_WIFI_INTC_DMA_CH2_EOT   (52 + MIPS_GIC_IRQ_BASE)
#define SIFLOWER_WIFI_INTC_DMA_CH3_EOT   (53 + MIPS_GIC_IRQ_BASE)

#define SIFLOWER_WIFI_INTC_LLI0          (54 + MIPS_GIC_IRQ_BASE)
#define SIFLOWER_WIFI_INTC_LLI1          (55 + MIPS_GIC_IRQ_BASE)
#define SIFLOWER_WIFI_INTC_LLI2          (56 + MIPS_GIC_IRQ_BASE)
#define SIFLOWER_WIFI_INTC_LLI3          (57 + MIPS_GIC_IRQ_BASE)
#define SIFLOWER_WIFI_INTC_LLI4          (58 + MIPS_GIC_IRQ_BASE)
#define SIFLOWER_WIFI_INTC_LLI5          (59 + MIPS_GIC_IRQ_BASE)
#define SIFLOWER_WIFI_INTC_LLI6          (60 + MIPS_GIC_IRQ_BASE)
#define SIFLOWER_WIFI_INTC_LLI7          (61 + MIPS_GIC_IRQ_BASE)
#define SIFLOWER_WIFI_INTC_LLI8          (62 + MIPS_GIC_IRQ_BASE)
#define SIFLOWER_WIFI_INTC_LLI9          (63 + MIPS_GIC_IRQ_BASE)

#define SIFLOWER_WIFI_INTC_CPU_SINGLE_5G    (64 + MIPS_GIC_IRQ_BASE)
//WIFI Inter Processor Communication
#define SIFLOWER_WIFI_INTC_IPC_HOST_5G      (65 + MIPS_GIC_IRQ_BASE)
//WIFI End Of Transfer interrupts: Last fragment of the channel link list has been processed
#define SIFLOWER_WIFI_INTC_DMA_CH0_EOT_5G   (66 + MIPS_GIC_IRQ_BASE)
#define SIFLOWER_WIFI_INTC_DMA_CH1_EOT_5G   (67 + MIPS_GIC_IRQ_BASE)
#define SIFLOWER_WIFI_INTC_DMA_CH2_EOT_5G   (68 + MIPS_GIC_IRQ_BASE)
#define SIFLOWER_WIFI_INTC_DMA_CH3_EOT_5G   (69 + MIPS_GIC_IRQ_BASE)
#define SIFLOWER_WIFI_INTC_LLI0_5G          (70 + MIPS_GIC_IRQ_BASE)
#define SIFLOWER_WIFI_INTC_LLI1_5G          (71 + MIPS_GIC_IRQ_BASE)
#define SIFLOWER_WIFI_INTC_LLI2_5G          (72 + MIPS_GIC_IRQ_BASE)
#define SIFLOWER_WIFI_INTC_LLI3_5G          (73 + MIPS_GIC_IRQ_BASE)
#define SIFLOWER_WIFI_INTC_LLI4_5G          (74 + MIPS_GIC_IRQ_BASE)
#define SIFLOWER_WIFI_INTC_LLI5_5G          (75 + MIPS_GIC_IRQ_BASE)
#define SIFLOWER_WIFI_INTC_LLI6_5G          (76 + MIPS_GIC_IRQ_BASE)
#define SIFLOWER_WIFI_INTC_LLI7_5G          (77 + MIPS_GIC_IRQ_BASE)
#define SIFLOWER_WIFI_INTC_LLI8_5G          (78 + MIPS_GIC_IRQ_BASE)
#define SIFLOWER_WIFI_INTC_LLI9_5G          (79 + MIPS_GIC_IRQ_BASE)

//WIFI LLI interrupts: Specific fragment of link list item has been processed
#define SIFLOWER_WIFI_INTC_LLI10         (96 + MIPS_GIC_IRQ_BASE)
#define SIFLOWER_WIFI_INTC_LLI11         (97 + MIPS_GIC_IRQ_BASE)
#define SIFLOWER_WIFI_INTC_LLI12         (98 + MIPS_GIC_IRQ_BASE)
#define SIFLOWER_WIFI_INTC_LLI13         (99 + MIPS_GIC_IRQ_BASE)
#define SIFLOWER_WIFI_INTC_LLI14         (100 + MIPS_GIC_IRQ_BASE)
#define SIFLOWER_WIFI_INTC_LLI15         (101 + MIPS_GIC_IRQ_BASE)

//WIFI DMA
#define SIFLOWER_WIFI_INTC_DMA_BUSERR    (102 + MIPS_GIC_IRQ_BASE)
#define SIFLOWER_WIFI_INTC_DMA_CH4_EOT   (103 + MIPS_GIC_IRQ_BASE)
// MAC HW
#define SIFLOWER_WIFI_INTC_MACTIMER      (104 + MIPS_GIC_IRQ_BASE)
#define SIFLOWER_WIFI_INTC_MACOTHER      (105 + MIPS_GIC_IRQ_BASE)
#define SIFLOWER_WIFI_INTC_MACRX         (106 + MIPS_GIC_IRQ_BASE)
#define SIFLOWER_WIFI_INTC_MACTX         (107 + MIPS_GIC_IRQ_BASE)
#define SIFLOWER_WIFI_INTC_MACINTGEN     (108 + MIPS_GIC_IRQ_BASE)
#define SIFLOWER_WIFI_INTC_MACPROT       (109 + MIPS_GIC_IRQ_BASE)

//WIFI Inter Processor Communication
#define SIFLOWER_WIFI_INTC_IPC0          (110 + MIPS_GIC_IRQ_BASE)
#define SIFLOWER_WIFI_INTC_IPC1          (111 + MIPS_GIC_IRQ_BASE)

//WIFI LLI interrupts: Specific fragment of link list item has been processed
#define SIFLOWER_WIFI_INTC_LLI10_5G         (112 + MIPS_GIC_IRQ_BASE)
#define SIFLOWER_WIFI_INTC_LLI11_5G         (113 + MIPS_GIC_IRQ_BASE)
#define SIFLOWER_WIFI_INTC_LLI12_5G         (114 + MIPS_GIC_IRQ_BASE)
#define SIFLOWER_WIFI_INTC_LLI13_5G         (115 + MIPS_GIC_IRQ_BASE)
#define SIFLOWER_WIFI_INTC_LLI14_5G         (116 + MIPS_GIC_IRQ_BASE)
#define SIFLOWER_WIFI_INTC_LLI15_5G         (117 + MIPS_GIC_IRQ_BASE)

//WIFI DMA
#define SIFLOWER_WIFI_INTC_DMA_BUSERR_5G    (118 + MIPS_GIC_IRQ_BASE)
#define SIFLOWER_WIFI_INTC_DMA_CH4_EOT_5G   (119 + MIPS_GIC_IRQ_BASE)

// MAC HW
#define SIFLOWER_WIFI_INTC_MACTIMER_5G      (120 + MIPS_GIC_IRQ_BASE)
#define SIFLOWER_WIFI_INTC_MACOTHER_5G      (121 + MIPS_GIC_IRQ_BASE)
#define SIFLOWER_WIFI_INTC_MACRX_5G         (122 + MIPS_GIC_IRQ_BASE)
#define SIFLOWER_WIFI_INTC_MACTX_5G         (123 + MIPS_GIC_IRQ_BASE)
#define SIFLOWER_WIFI_INTC_MACINTGEN_5G     (124 + MIPS_GIC_IRQ_BASE)
#define SIFLOWER_WIFI_INTC_MACPROT_5G       (125 + MIPS_GIC_IRQ_BASE)

//WIFI Inter Processor Communication
#define SIFLOWER_WIFI_INTC_IPC0_5G          (126 + MIPS_GIC_IRQ_BASE)
#define SIFLOWER_WIFI_INTC_IPC1_5G          (127 + MIPS_GIC_IRQ_BASE)

//WIFI IQ TEST ENGINE buffer full interruption
#define SIFLOWER_WIFI_INTC_IQR_LOWRAM_FULL   (192 + MIPS_GIC_IRQ_BASE)
#define SIFLOWER_WIFI_INTC_IQR_HIGHRAM_FULL  (193 + MIPS_GIC_IRQ_BASE)
#define SIFLOWER_WIFI_INTC_IQP_LOWRAM_FULL   (194 + MIPS_GIC_IRQ_BASE)
#define SIFLOWER_WIFI_INTC_IQP_HIGHRAM_FULL  (195 + MIPS_GIC_IRQ_BASE)

//WIFI Inter Processor Communication
#define SIFLOWER_WIFI_INTC_IPC2          (200 + MIPS_GIC_IRQ_BASE)
#define SIFLOWER_WIFI_INTC_IPC3          (201 + MIPS_GIC_IRQ_BASE)

//WIFI PHY HW
#define SIFLOWER_WIFI_INTC_MODEM         (202 + MIPS_GIC_IRQ_BASE)
#define SIFLOWER_WIFI_INTC_RC            (203 + MIPS_GIC_IRQ_BASE)

//WIFI Inter Processor Communication
#define SIFLOWER_WIFI_INTC_IPC2_5G          (204 + MIPS_GIC_IRQ_BASE)
#define SIFLOWER_WIFI_INTC_IPC3_5G          (205 + MIPS_GIC_IRQ_BASE)

//WIFI PHY HW
#define SIFLOWER_WIFI_INTC_MODEM_5G         (206 + MIPS_GIC_IRQ_BASE)
#define SIFLOWER_WIFI_INTC_RC_5G            (207 + MIPS_GIC_IRQ_BASE)

#endif /* !(_MIPS_SF16A18INT_H) */
