#ifndef COMPAT_AUTOCONF_INCLUDED
#define COMPAT_AUTOCONF_INCLUDED
/*
 * Automatically generated file, don't edit!
 * Changes will be overwritten
 */

#define CPTCFG_WIRELESS 1
#define CPTCFG_NET_CORE 1
#define CPTCFG_EXPERT 1
#define CPTCFG_BP_MODULES 1
#define CPTCFG_BPAUTO_RHASHTABLE 1
#define CPTCFG_CFG80211_MODULE 1
#define CPTCFG_NL80211_TESTMODE 1
#define CPTCFG_CFG80211_CERTIFICATION_ONUS 1
#define CPTCFG_CFG80211_DEBUGFS 1
#define CPTCFG_CFG80211_INTERNAL_REGDB 1
#define CPTCFG_CFG80211_WEXT 1
#define CPTCFG_MAC80211_MODULE 1
#define CPTCFG_MAC80211_HAS_RC 1
#define CPTCFG_MAC80211_RC_MINSTREL 1
#define CPTCFG_MAC80211_RC_MINSTREL_HT 1
#define CPTCFG_MAC80211_RC_MINSTREL_VHT 1
#define CPTCFG_MAC80211_RC_DEFAULT_MINSTREL 1
#define CPTCFG_MAC80211_RC_DEFAULT "minstrel_ht"
#define CPTCFG_MAC80211_MESH 1
#define CPTCFG_MAC80211_DEBUGFS 1
#define CPTCFG_MAC80211_STA_HASH_MAX_SIZE 0
#define CPTCFG_WLAN 1
#define CPTCFG_WLAN_VENDOR_ADMTEK 1
#define CPTCFG_WLAN_VENDOR_ATH 1
#define CPTCFG_WLAN_VENDOR_ATMEL 1
#define CPTCFG_WLAN_VENDOR_BROADCOM 1
#define CPTCFG_WLAN_VENDOR_INTEL 1
#define CPTCFG_WLAN_VENDOR_INTERSIL 1
#define CPTCFG_WLAN_VENDOR_MARVELL 1
#define CPTCFG_WLAN_VENDOR_MEDIATEK 1
#define CPTCFG_WLAN_VENDOR_RALINK 1
#define CPTCFG_WLAN_VENDOR_REALTEK 1
#define CPTCFG_WLAN_VENDOR_RSI 1
#define CPTCFG_WLAN_VENDOR_ST 1
#define CPTCFG_WLAN_VENDOR_TI 1
#define CPTCFG_WLAN_VENDOR_ZYDAS 1
#define CPTCFG_MAC80211_HWSIM_MODULE 1
#endif /* COMPAT_AUTOCONF_INCLUDED */
